name: Containerize (production)
on:
  push:
    tags:
      - v0.*
      - v1.*

jobs:
  build:
    name: Build the Docker image and push to GHCR
    runs-on: ubuntu-latest
    env:
      APP_HOST: ${{ secrets.APP_HOST }}
      APP_ADMIN_EMAIL: ${{ secrets.APP_ADMIN_EMAIL }}
      APP_ADMIN_PASSWORD: ${{ secrets.APP_ADMIN_PASSWORD }}
      APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      MONGO_INITDB_DATABASE: ${{ secrets.MONGO_INITDB_DATABASE }}
      RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
      RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCH_SECRET_KEY }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the image and push to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}:latest
          pull: true
          push: true
          build-args: |
            APP_HOST=${{ secrets.APP_HOST }}
            APP_ADMIN_EMAIL=${{ secrets.APP_ADMIN_EMAIL }}
            APP_ADMIN_PASSWORD=${{ secrets.APP_ADMIN_PASSWORD }}
            APP_JWT_SECRET=${{ secrets.APP_JWT_SECRET }}
            MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
            MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
            MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }}
            RECAPTCHA_SITE_KEY=${{ secrets.RECAPTCHA_SITE_KEY }}
            RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCH_SECRET_KEY }}
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=${{ secrets.REDIS_PORT }}
        env:
          APP_HOST: ${{ secrets.APP_HOST }}
          APP_ADMIN_EMAIL: ${{ secrets.APP_ADMIN_EMAIL }}
          APP_ADMIN_PASSWORD: ${{ secrets.APP_ADMIN_PASSWORD }}
          APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
          MONGO_INITDB_DATABASE: ${{ secrets.MONGO_INITDB_DATABASE }}
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCH_SECRET_KEY }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
